"""Setup utilities for Dav."""

from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt

console = Console()


def run_setup() -> None:
    """Run initial setup for Dav."""
    console.print(Panel.fit(
        "[bold green]Dav Setup[/bold green]",
        border_style="green"
    ))
    
    dav_dir = Path.home() / ".dav"
    env_file = dav_dir / ".env"
    
    # Create .dav directory
    console.print("\n[bold]Step 1:[/bold] Creating .dav directory...")
    try:
        dav_dir.mkdir(parents=True, exist_ok=True)
        console.print(f"[green]✓[/green] Created directory: {dav_dir}")
    except Exception as e:
        console.print(f"[red]✗[/red] Error creating directory: {e}")
        return
    
    # Check if .env already exists
    env_file_exists = env_file.exists()
    env_file_empty = False
    
    if env_file_exists:
        # Check if file is empty or only contains whitespace
        try:
            with open(env_file, "r") as f:
                content = f.read().strip()
                env_file_empty = len(content) == 0
        except Exception:
            env_file_empty = False
        
        if env_file_empty:
            console.print(f"\n[yellow]⚠[/yellow] Configuration file exists but is empty: {env_file}")
            console.print("[yellow]The file will be overwritten with new configuration.[/yellow]")
        else:
            console.print(f"\n[yellow]⚠[/yellow] Configuration file already exists: {env_file}")
            overwrite = Prompt.ask("Overwrite existing .env file?", choices=["y", "n"], default="n")
            if overwrite.lower() != "y":
                console.print("[yellow]Skipping .env file creation.[/yellow]")
                return
    
    # Ask for backend preference
    console.print("\n[bold]Step 2:[/bold] Configure API key")
    backend = Prompt.ask(
        "Which AI backend do you want to use?",
        choices=["openai", "anthropic"],
        default="openai"
    )
    
    # Ask for API key
    api_key = Prompt.ask(
        f"Enter your {backend.upper()} API key",
        password=True
    )
    
    if not api_key:
        console.print("[red]✗[/red] API key is required. Setup cancelled.")
        return
    
    # Create .env file
    console.print("\n[bold]Step 3:[/bold] Creating .env file...")
    
    if backend == "openai":
        env_content = f"""# Dav Configuration
# Generated by: dav --setup

# OpenAI Configuration
OPENAI_API_KEY={api_key}
DAV_BACKEND=openai
DAV_DEFAULT_MODEL=gpt-4-turbo-preview

# Optional: Anthropic Configuration (if you want to switch later)
# ANTHROPIC_API_KEY=your_anthropic_api_key_here
# DAV_ANTHROPIC_MODEL=claude-3-5-sonnet-20241022

# Permissions
DAV_ALLOW_EXECUTE=false

# History
DAV_HISTORY_ENABLED=true

# Sessions
DAV_SESSION_DIR=~/.dav/sessions
"""
    else:  # anthropic
        env_content = f"""# Dav Configuration
# Generated by: dav --setup

# Anthropic Configuration
ANTHROPIC_API_KEY={api_key}
DAV_BACKEND=anthropic
DAV_DEFAULT_MODEL=claude-3-5-sonnet-20241022

# Optional: OpenAI Configuration (if you want to switch later)
# OPENAI_API_KEY=your_openai_api_key_here
# DAV_OPENAI_MODEL=gpt-4-turbo-preview

# Permissions
DAV_ALLOW_EXECUTE=false

# History
DAV_HISTORY_ENABLED=true

# Sessions
DAV_SESSION_DIR=~/.dav/sessions
"""
    
    try:
        # Write the file
        with open(env_file, "w") as f:
            f.write(env_content)
        
        # Verify the file was written correctly
        with open(env_file, "r") as f:
            written_content = f.read()
            if len(written_content.strip()) == 0:
                console.print(f"[red]✗[/red] Error: File was written but appears empty!")
                console.print("[yellow]This might be a permissions issue. Try creating the file manually.[/yellow]")
                return
            if api_key not in written_content:
                console.print(f"[yellow]⚠[/yellow] Warning: API key might not have been written correctly.")
                console.print("[yellow]Please verify the file contents manually.[/yellow]")
        
        console.print(f"[green]✓[/green] Created configuration file: {env_file}")
        console.print(f"[green]✓[/green] File size: {len(env_content)} bytes")
    except PermissionError as e:
        console.print(f"[red]✗[/red] Permission denied: Cannot write to {env_file}")
        console.print("[yellow]Try running with appropriate permissions or create the file manually.[/yellow]")
        return
    except Exception as e:
        console.print(f"[red]✗[/red] Error creating .env file: {e}")
        return
    
    # Success message
    console.print("\n[bold green]✓ Setup complete![/bold green]\n")
    console.print("You can now use Dav. Try running:")
    console.print("  [cyan]dav \"how do I check disk usage?\"[/cyan]\n")
    console.print("To edit your configuration later:")
    console.print(f"  [cyan]nano {env_file}[/cyan]\n")

